name: coolapp

services:
  web:
    build: ./web
    env_file: ./web/web.env
    ports:
      - "8000:3000"
  ml:
    build: ./ml
    env_file: ./ml/ml.env
    # tty: true
    # command: bash
  db:
    image: mongo
    ports:
      - "8001:27017"
    volumes:
      - type: volume
        source: coolapp_db_data
        target: /data/db

volumes:
  coolapp_db_data: